## This file is a general .xdc for the Basys3 rev B board
## To use it in a project:
## - uncomment the lines corresponding to used pins
## - rename the used ports (in each line, after get_ports) according to the top level signal names in the project

## Clock signal
#set_property PACKAGE_PIN W5 [get_ports clk]
#set_property IOSTANDARD LVCMOS33 [get_ports clk]
#create_clock -add -name sys_clk_pin -period 10.00 -waveform {0 5} [get_ports clk]

## Switches
set_property PACKAGE_PIN V17 [get_ports {challenge_in_0[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {challenge_in_0[0]}]
set_property PACKAGE_PIN V16 [get_ports {challenge_in_0[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {challenge_in_0[1]}]
set_property PACKAGE_PIN W16 [get_ports {challenge_in_0[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {challenge_in_0[2]}]
set_property PACKAGE_PIN W17 [get_ports {challenge_in_0[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {challenge_in_0[3]}]
set_property PACKAGE_PIN W15 [get_ports {challenge_in_0[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {challenge_in_0[4]}]
set_property PACKAGE_PIN V15 [get_ports {challenge_in_0[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {challenge_in_0[5]}]
set_property PACKAGE_PIN W14 [get_ports {challenge_in_0[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {challenge_in_0[6]}]
set_property PACKAGE_PIN W13 [get_ports {challenge_in_0[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {challenge_in_0[7]}]
set_property PACKAGE_PIN V2 [get_ports {challenge_in_0[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {challenge_in_0[8]}]
set_property PACKAGE_PIN T3 [get_ports {challenge_in_0[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {challenge_in_0[9]}]
set_property PACKAGE_PIN T2 [get_ports {challenge_in_0[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {challenge_in_0[10]}]
set_property PACKAGE_PIN R3 [get_ports {challenge_in_0[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {challenge_in_0[11]}]
set_property PACKAGE_PIN W2 [get_ports {challenge_in_0[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {challenge_in_0[12]}]
set_property PACKAGE_PIN U1 [get_ports {challenge_in_0[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {challenge_in_0[13]}]
set_property PACKAGE_PIN T1 [get_ports {challenge_in_0[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {challenge_in_0[14]}]
set_property PACKAGE_PIN R2 [get_ports {challenge_in_0[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {challenge_in_0[15]}]

## LEDs
set_property PACKAGE_PIN U16 [get_ports {response_out_0[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {response_out_0[0]}]
set_property PACKAGE_PIN E19 [get_ports {response_out_0[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {response_out_0[1]}]
set_property PACKAGE_PIN U19 [get_ports {response_out_0[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {response_out_0[2]}]
set_property PACKAGE_PIN V19 [get_ports {response_out_0[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {response_out_0[3]}]
set_property PACKAGE_PIN W18 [get_ports {response_out_0[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {response_out_0[4]}]
set_property PACKAGE_PIN U15 [get_ports {response_out_0[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {response_out_0[5]}]
set_property PACKAGE_PIN U14 [get_ports {response_out_0[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {response_out_0[6]}]
set_property PACKAGE_PIN V14 [get_ports {response_out_0[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {response_out_0[7]}]
#set_property PACKAGE_PIN V13 [get_ports {response_out_0[8]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {response_out_0[8]}]
#set_property PACKAGE_PIN V3 [get_ports {response_out_0[9]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {response_out_0[9]}]
#set_property PACKAGE_PIN W3 [get_ports {response_out_0[10]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {response_out_0[10]}]
#set_property PACKAGE_PIN U3 [get_ports {response_out_0[11]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {response_out_0[11]}]
#set_property PACKAGE_PIN P3 [get_ports {response_out_0[12]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {response_out_0[12]}]
#set_property PACKAGE_PIN N3 [get_ports {response_out_0[13]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {response_out_0[13]}]
set_property PACKAGE_PIN P1 [get_ports {valid_out_0}]
set_property IOSTANDARD LVCMOS33 [get_ports {valid_out_0}]
set_property PACKAGE_PIN L1 [get_ports {control_out_0}]
set_property IOSTANDARD LVCMOS33 [get_ports {control_out_0}]

##Buttons
set_property PACKAGE_PIN U18 [get_ports reset]
set_property IOSTANDARD LVCMOS33 [get_ports reset]
set_property PACKAGE_PIN T18 [get_ports start_in_0]
set_property IOSTANDARD LVCMOS33 [get_ports start_in_0]
#set_property PACKAGE_PIN W19 [get_ports btnL]
#set_property IOSTANDARD LVCMOS33 [get_ports btnL]
#set_property PACKAGE_PIN T17 [get_ports btnR]
#set_property IOSTANDARD LVCMOS33 [get_ports btnR]
#set_property PACKAGE_PIN U17 [get_ports btnD]
#set_property IOSTANDARD LVCMOS33 [get_ports btnD]

set_property IOSTANDARD LVCMOS33 [get_ports {challenge_in[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {challenge_in[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {challenge_in[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {challenge_in[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {challenge_in[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {challenge_in[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {challenge_in[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {challenge_in[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {challenge_in[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {challenge_in[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {challenge_in[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {challenge_in[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {challenge_in[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {challenge_in[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {challenge_in[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {challenge_in[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {response_out[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {response_out[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {response_out[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {response_out[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {response_out[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {response_out[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {response_out[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {response_out[0]}]
set_property PACKAGE_PIN R2 [get_ports {challenge_in[15]}]
set_property PACKAGE_PIN T1 [get_ports {challenge_in[14]}]
set_property PACKAGE_PIN U1 [get_ports {challenge_in[13]}]
set_property PACKAGE_PIN W2 [get_ports {challenge_in[12]}]
set_property PACKAGE_PIN R3 [get_ports {challenge_in[11]}]
set_property PACKAGE_PIN T2 [get_ports {challenge_in[10]}]
set_property PACKAGE_PIN T3 [get_ports {challenge_in[9]}]
set_property PACKAGE_PIN V2 [get_ports {challenge_in[8]}]
set_property PACKAGE_PIN W13 [get_ports {challenge_in[7]}]
set_property PACKAGE_PIN W14 [get_ports {challenge_in[6]}]
set_property PACKAGE_PIN V15 [get_ports {challenge_in[5]}]
set_property PACKAGE_PIN W15 [get_ports {challenge_in[4]}]
set_property PACKAGE_PIN W17 [get_ports {challenge_in[3]}]
set_property PACKAGE_PIN W16 [get_ports {challenge_in[2]}]
set_property PACKAGE_PIN V16 [get_ports {challenge_in[1]}]
set_property PACKAGE_PIN V17 [get_ports {challenge_in[0]}]
set_property PACKAGE_PIN V14 [get_ports {response_out[7]}]
set_property PACKAGE_PIN U14 [get_ports {response_out[6]}]
set_property PACKAGE_PIN U15 [get_ports {response_out[5]}]
set_property PACKAGE_PIN W18 [get_ports {response_out[4]}]
set_property PACKAGE_PIN V19 [get_ports {response_out[3]}]
set_property PACKAGE_PIN U19 [get_ports {response_out[2]}]
set_property PACKAGE_PIN E19 [get_ports {response_out[1]}]
set_property PACKAGE_PIN U16 [get_ports {response_out[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property PACKAGE_PIN W5 [get_ports clk]
set_property PACKAGE_PIN L1 [get_ports control_out]
set_property IOSTANDARD LVCMOS33 [get_ports control_out]
set_property PACKAGE_PIN P1 [get_ports valid_out]
set_property PACKAGE_PIN T18 [get_ports start_in]
set_property IOSTANDARD LVCMOS33 [get_ports start_in]
set_property IOSTANDARD LVCMOS33 [get_ports valid_out]
